### PR TITLE
Update README.md in main

### PR DESCRIPTION
**Pull request by BunradarCH**
Fix readme

### CODE REVIEW

**Review by doungnapat27 — APPROVED** [review]
Okie Dokie

**Comment by cragkhit** [comment]
Hi. Is this the project phase 2 repo? Do you have a separate repo from phase 1? @doungnapat27

**Comment by doungnapat27** [comment]
> Hi. Is this the project phase 2 repo? Do you have a separate repo from phase 1? @doungnapat27

Yes ka aj, This is the repo for the project both for Practical SE and QA Project phase2. Our repo for phase 1 is [here](https://github.com/ICT-Mahidol/2023-ITCS473-TeamNeeOilKhum)

**Comment by cragkhit** [comment]
@doungnapat27 I see. Ok. Can you put the link to this repo on the phase 1 repo as well?

**Comment by doungnapat27** [comment]
> @doungnapat27 I see. Ok. Can you put the link to this repo on the phase 1 repo as well?

Roger that🫡

**Pull request merged**
